language: java
sudo: false

jdk:
  - oraclejdk8

# only build master and the MATH_3_X branch
branches:
  only:
    - master
    - MATH_3_X
    - ekstazi



before_script:
  - cp -f -r ~/.ekstazi ./

script:
  - mvn -Pekstazi test
  - pwd
  - find -name .ekstazi
  - cp -f -r ./.ekstazi ~

cache:
  directories:
  - ~/.ekstazi
